"use client";
import { useEffect } from "react";
const invitationUrl = "https://tally.so/r/b5XZp6";
const stories = [
  { image:"/assets/portrait-balcony.png", label:"Home, in the everyday", quote:"The places where people know you best." },
  { image:"/assets/portrait-cafe.png", label:"An unhurried call home", quote:"A little advice can travel far." },
  { image:"/assets/mist-walk.png", label:"Back home for a family gathering", quote:"Some arrivals feel familiar before they begin.", wide:true },
  { image:"/assets/portrait-man.png", label:"Making a life, keeping home close", quote:"A new chapter still has its roots.", wide:true },
  { image:"/assets/daylight.png", label:"A familiar corner", quote:"The people who care make a place feel like home." },
  { image:"/assets/conversation-prompt.png", label:"A conversation worth making time for", quote:"Good introductions leave room for everyone to be heard." },
];
export default function Home() {
  useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>entry.isIntersecting&&entry.target.classList.add("on")),{threshold:.14}); document.querySelectorAll(".reveal:not(.hero .reveal)").forEach(el=>observer.observe(el)); return()=>observer.disconnect();},[]);
  return <main>
    <header className="nav"><div className="nav-inner wrap"><a className="brand" href="#top" aria-label="Sainoo home"><img className="brand-mark" src="/sainoo-mark.png" alt=""/><span className="brand-name">Sainoo</span><span className="brand-script">साइनो</span></a><nav className="nav-links nav-invite-only" aria-label="Main navigation"><a className="nav-cta" href={invitationUrl} target="_blank" rel="noreferrer">Ask for an invitation</a></nav></div></header>
    <style jsx global>{`@media(max-width:760px){.nav-links.nav-invite-only{position:static;display:flex;flex-direction:row;opacity:1;visibility:visible;background:transparent;font:inherit}.nav-links.nav-invite-only .nav-cta{padding:9px 13px;border:1px solid rgba(242,241,235,.65);border-radius:100px;color:var(--paper-light);font-size:11px}}`}</style>
    <section className="hero" id="top"><div className="hero-image"/><div className="hero-overlay"/><div className="thread-hero"><span/><b/></div><div className="hero-content wrap"><div className="hero-copy"><h1 className="reveal delay">Some introductions<br/>deserve to be<br/><em>made well.</em></h1></div><div className="hero-bottom reveal delay"><p>For people who call Sikkim home—and the families and friends who want good things for them.</p><a className="button" href={invitationUrl} target="_blank" rel="noreferrer">Ask for an invitation ↗</a></div></div></section>
    <section className="prompt-section" id="conversation"><div className="weave-divider"/><div className="prompt-grid wrap"><div className="reveal"><h2>Introductions,<br/>made <em>thoughtfully.</em></h2><p className="prompt-copy">Sainoo begins with interest, not a profile. We take time to understand the person, the context and the kind of future they hope to build.</p><ol className="process-list"><li><span>01</span><strong>Begin with interest</strong><p>Let us know you would like to hear more.</p></li><li><span>02</span><strong>Make a considered introduction</strong><p>When the time is right, the first conversation can begin.</p></li><li><span>03</span><strong>Let the conversation find its pace</strong><p>With care, privacy and room for everyone to be heard.</p></li></ol></div><figure className="prompt-media reveal"><img src="/assets/conversation-prompt.png" alt="Two people sharing a thoughtful conversation in a calm Gangtok setting"/><figcaption className="prompt-card">A beginning, not a profile.</figcaption></figure></div></section>
    <section className="belonging" id="stories"><div className="belonging-head wrap"><div className="reveal"><h2>Every introduction has <em>a wider circle.</em></h2><p className="belonging-copy">Sainoo is for people finding their own way—and for parents, siblings and friends who want to help with care.</p><p className="scroll-hint"><span/>A few familiar moments</p></div></div><div className="gallery" aria-label="Moments around a considered introduction">{stories.map(story=><figure className={`story${story.wide?" wide":""}`} key={story.label}><img src={story.image} alt={story.label}/><figcaption className="story-caption"><small>{story.label}</small><strong>“{story.quote}”</strong></figcaption></figure>)}</div></section>
    <section className="invite" id="invite"><div className="invite-grid wrap"><div className="reveal"><h2>A good beginning<br/><em>starts with interest.</em></h2><p className="invite-copy">For yourself, or for someone close to you, leave us a way to get in touch.</p><p className="invite-assurance">The person being introduced always decides the pace. Family can be involved as much—or as little—as feels right.</p></div><div className="reveal"><figure className="pinned-photo"><img src="/assets/portrait-man.png" alt="Portrait used as a prototype for the early interest circle"/><figcaption>SAINOO / EARLY INTEREST</figcaption></figure><a className="invite-button" href={invitationUrl} target="_blank" rel="noreferrer">Ask for an invitation <span aria-hidden="true">↗</span></a></div></div><footer className="wrap"><span>© 2026 Sainoo · Thoughtful introductions</span><span>Gangtok · Sikkim · India</span></footer></section>
  </main>;
}
